namespace ProgrammingGameApi.Services
{
    public enum SnippetLanguageCode
    {
        CSharp = 1,
        VB_NET = 2,
        FSharp = 3,
        Java = 4,
        Python = 5,
        C_gcc = 6,
        CPlusPlus_gcc = 7,
        Php = 8,
        Pascal = 9,
        Objective_C = 10,
        Haskell = 11,
        Ruby = 12,
        Perl = 13,
        Lua = 14,
        Nasm = 15,
        Sql_Server = 16,
        Javascript = 17,
        Lisp = 18,
        Prolog = 19,
        Go = 20,
        Scala = 21,
        Scheme = 22,
        Node_js = 23,
        Python_3 = 24,
        Octave = 25,
        C_clang = 26,
        CPlusPLus_clang = 27,
        CPlusPlus_VCPlusPLus = 28,
        C_vc= 29,
        D = 30,
        R = 31,
        Tcl = 32,
        MySQL = 33,
        PostgreSQL = 34,
        Oracle = 35,
        Swift = 37,
        Bash = 38,
        Ada = 39,
        Erlang = 40,
        Elixir = 41,
        Ocaml = 42,
        Kotlin = 43,
        BrainCENSORED = 44,
        Fortran = 45,
        Rust = 46,
        Clojure = 47
    }
}